name: Release to Cloudsmith
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest
    name: Raw File Push Demo
    env:
      GOOS: linux
      GOARCH: amd64
      RELEASE: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4 # For cloudsmith-cli
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18'
      - run: go build -ldflags "-s -w" -o bin && tar -czvf sa-collector-$RELEASE-$GOOS-$GOARCH.tar.gz bin
        shell: bash

#      - name: Push
#        id: push
#        uses: cloudsmith-io/action@v0.5.2 # pin 0.5.2: its code reviewed
#        with:
#          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
#          command: "push"
#          format: "raw"
#          owner: "vinted"
#          repo: "raw-hosted-security"
#          file: "test/fixture/raw_file.txt"
#          version: ${{ github.ref_name }}