name: Lint-Jobs
on:
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.24.2
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@7ecb048b56b28747ce02304a64cbef5daf45d94d
        with:
          version: latest
          args: --timeout 3m --verbose